# Generated by Django 5.1.1 on 2024-09-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npjAirport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='csit',
            table='csit',
        ),
    ]
